// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVE2T4pdanGujdBCMdgqt_zwpIDHaqcY',
    appId: '1:666258012724:web:8b192437d4ba4eb9fe2861',
    messagingSenderId: '666258012724',
    projectId: 'e-commerse-app-580fd',
    authDomain: 'e-commerse-app-580fd.firebaseapp.com',
    storageBucket: 'e-commerse-app-580fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrlu5dJCd6xlvoHIxstzBYJu3xf5RBkgs',
    appId: '1:666258012724:android:973ed8b54f79198ffe2861',
    messagingSenderId: '666258012724',
    projectId: 'e-commerse-app-580fd',
    storageBucket: 'e-commerse-app-580fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOsOZzLNdErhXGYk2rlESZ4bHGaGwiqig',
    appId: '1:666258012724:ios:53bead1cc35c66dcfe2861',
    messagingSenderId: '666258012724',
    projectId: 'e-commerse-app-580fd',
    storageBucket: 'e-commerse-app-580fd.appspot.com',
    iosClientId: '666258012724-h89vjjr241hveuc641j0lpm2jjj8fec3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommApp',
  );
}
